### ISSUE TITLE
Transfer ownership to Smallrivers?

### ISSUE THREAD

**Issue by rborer** [shmish111/clj-cron-parse#4]
Hi David,

Hope all is well with you.

I just noticed your comment on https://github.com/shmish111/clj-cron-parse/pull/3#discussion_r374559760 . Would you be interested in transferring this library to Smallrivers? We're still using it within the scheduler you wrote back in time :wink: .

Best,
Reynald

**Comment by shmish111** [comment]
Hi Reynald!

Absolutely, shall I just transfer ownership of the github repo and you can
add your own version on clojars?

**Comment by rborer** [comment]
Sure, I'll republish to clojars under our own group ID. Whenever you're ready transfer the repo to my user directly. Thanks!

**Comment by shmish111** [comment]
oh "You don’t have the permission to create public repositories on
smallrivers"

Doesn't it just make sense for you to fork the repo and I can put a
deprecated notice on my version. I'll investigate if I can do the same with
clojars.

**Comment by rborer** [comment]
@shmish111 thanks a lot.

Cheers from Switzerland :smile:

**Comment by shmish111** [comment]
Done. Can you keep me having access to this repo though.

**Comment by rborer** [comment]
Sure, I just invited you back.

**Comment by rborer** [comment]
@shmish111 Hey David, mind adding me into the clojars group so I can deploy newer versions? Thanks.

**Comment by shmish111** [comment]
Hi,

I've added you're personal account to the group, let me know if you have
any issues.

David

**Comment by rborer** [comment]
Thanks David. I think we're now all set with the ownership transfer so I'll close this issue.
